name: Publish to WordPress

on:
  #workflow_run:
  #  workflows: ["Generate Daily Markdown"]
  #  types: [completed]
  workflow_dispatch:  # 手动触发

jobs:
  publish_to_wordpress:
    runs-on: ubuntu-latest
    env:
      PUBLISH_ENABLED: 'false'  # 设置环境变量

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: ${{ env.PUBLISH_ENABLED == 'true' }}  
      run: |
        pip install requests
        pip install markdown 

    - name: Publish to WordPress
      if: ${{ env.PUBLISH_ENABLED == 'true' }}  
      env:
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
      run: |
        python scripts/publish_to_wordpress.py